typedef struct {long attr[3];} yyATTRIBUTES;
#define YYSTYPE yyATTRIBUTES
extern YYSTYPE yylval;

#define id 257
#define int_lit 258
#define real_lit 259
#define text_lit 260
#define char_lit 261
#define eofile 262
#define nextunit 263
#define filename 264
#define yytk_SEMICOLON 265
#define yytk_PLUS_PLUS 266
#define yytk_BAR_BAR 267
#define yytk_BAR_POWER_BAR 268
#define yytk_BAR_EQUAL_BAR 269
#define yytk_TILDE 270
#define yytk_BACKSLASH_SLASH 271
#define yytk_EQUAL_GREATER 272
#define yytk_MINUS 273
#define yytk_PLUS 274
#define yykw_wait 275
#define yykw_rng 276
#define yykw_dom 277
#define yykw_tl 278
#define yykw_hd 279
#define yykw_elems 280
#define yykw_inds 281
#define yykw_len 282
#define yykw_card 283
#define yykw_real 284
#define yykw_int 285
#define yykw_abs 286
#define yytk_ASTERISK_ASTERISK 287
#define yykw_inter 288
#define yytk_SHARP 289
#define yytk_SLASH 290
#define yytk_ASTERISK 291
#define yytk_EXCLAM_EXCLAM 292
#define yykw_union 293
#define yytk_BACKSLASH 294
#define yytk_TILDE_i_BLANK_s_BLANK_i_BLANK_n_BLANK 295
#define yykw_isin 296
#define yytk_LESS_LESS_EQUAL 297
#define yytk_GREATER_GREATER_EQUAL 298
#define yytk_LESS_LESS 299
#define yytk_GREATER_GREATER 300
#define yytk_LESS_EQUAL 301
#define yytk_GREATER_EQUAL 302
#define yytk_LESS 303
#define yytk_GREATER 304
#define yytk_TILDE_EQUAL 305
#define yytk_DOT 306
#define yytk_POWER 307
#define yykw_until 308
#define yykw_do 309
#define yykw_while 310
#define yykw_case 311
#define yykw_elsif 312
#define yykw_then 313
#define yykw_if 314
#define yykw_let 315
#define yytk_EXCLAM 316
#define yytk_QUESTIONM 317
#define yykw_initialise 318
#define yykw_always 319
#define yykw_as 320
#define yykw_post 321
#define yykw_pre 322
#define yytk_e_BLANK_x_BLANK_i_BLANK_s_BLANK_t_BLANK_s_BLANK_EXCLAM 323
#define yykw_exists 324
#define yytk_MINUS_BACKSLASH 325
#define yytk_PLUS_GREATER 326
#define yytk_DOT_GREATER 327
#define yytk_LESS_DOT 328
#define yytk_DOT_DOT 329
#define yykw_swap 330
#define yykw_stop 331
#define yykw_skip 332
#define yykw_chaos 333
#define yytk_BACKQUOTE 334
#define yykw_false 335
#define yykw_true 336
#define yykw_any 337
#define yykw_out 338
#define yykw_write 339
#define yykw_read 340
#define yykw_of 341
#define yykw_array 342
#define yytk_BAR_RBRACE 343
#define yytk_LBRACE_BAR 344
#define yytk_MINUS_GREATER 345
#define yytk_MINUS_TILDE_MINUS_GREATER 346
#define yytk_MINUS_TILDE_m_BLANK_MINUS_GREATER 347
#define yytk_MINUS_m_BLANK_MINUS_GREATER 348
#define yytk_MINUS_i_BLANK_n_BLANK_f_BLANK_l_BLANK_i_BLANK_s_BLANK_t_BLANK 349
#define yytk_MINUS_l_BLANK_i_BLANK_s_BLANK_t_BLANK 350
#define yytk_MINUS_i_BLANK_n_BLANK_f_BLANK_s_BLANK_e_BLANK_t_BLANK 351
#define yytk_MINUS_s_BLANK_e_BLANK_t_BLANK 352
#define yytk_GREATER_LESS 353
#define yykw_Char 354
#define yykw_Text 355
#define yykw_Real 356
#define yykw_Nat 357
#define yykw_Int 358
#define yykw_Bool 359
#define yykw_Unit 360
#define yytk_RBRACE 361
#define yytk_LBRACE 362
#define yytk_BAR_RBRACKET 363
#define yytk_LBRACKET_BAR 364
#define yykw_use 365
#define yykw_hide 366
#define yykw_with 367
#define yykw_extend 368
#define yykw_class 369
#define yytk_l_BLANK_t_BLANK_l_BLANK_UNDERSCORE_a_BLANK_s_BLANK_s_BLANK_e_BLANK_r_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK 370
#define yykw_all 371
#define yytk_COLON_MINUS 372
#define yytk_LPAREN_LBRACKET_EQUAL_RBRACKET 373
#define yytk_EQUAL_EQUAL_GREATER 374
#define yykw_else 375
#define yytk_LBRACKET_EQUAL_RBRACKET 376
#define yytk_LBRACKET_GREATER_RBRACKET 377
#define yykw_where 378
#define yytk_t_BLANK_r_BLANK_a_BLANK_n_BLANK_s_BLANK_i_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK_UNDERSCORE_r_BLANK_u_BLANK_l_BLANK_e_BLANK_s_BLANK 379
#define yytk_t_BLANK_r_BLANK_a_BLANK_n_BLANK_s_BLANK_i_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK_UNDERSCORE_r_BLANK_e_BLANK_l_BLANK_a_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK 380
#define yytk_SLASH_BACKSLASH 381
#define yytk_i_BLANK_n_BLANK_i_BLANK_t_BLANK_UNDERSCORE_c_BLANK_o_BLANK_n_BLANK_s_BLANK_t_BLANK_r_BLANK_a_BLANK_i_BLANK_n_BLANK_t_BLANK 382
#define yykw_local 383
#define yytk_t_BLANK_r_BLANK_a_BLANK_n_BLANK_s_BLANK_i_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK_UNDERSCORE_s_BLANK_y_BLANK_s_BLANK_t_BLANK_e_BLANK_m_BLANK 384
#define yytk_t_BLANK_e_BLANK_s_BLANK_t_BLANK_UNDERSCORE_c_BLANK_a_BLANK_s_BLANK_e_BLANK 385
#define yykw_channel 386
#define yytk_COLON_EQUAL 387
#define yykw_variable 388
#define yykw_is 389
#define yykw_value 390
#define yytk_COLON_COLON 391
#define yytk_LESS_MINUS_GREATER 392
#define yytk_UNDERSCORE 393
#define yytk_BAR 394
#define yytk_EQUAL_EQUAL 395
#define yykw_type 396
#define yytk_RBRACKET 397
#define yytk_LBRACKET 398
#define yytk_EQUAL 399
#define yykw_for 400
#define yytk_LBRACKET_EQUAL 401
#define yytk_LBRACE_EQUAL 402
#define yytk_RPAREN 403
#define yytk_LPAREN 404
#define yytk_BAR_MINUS 405
#define yykw_in 406
#define yytk_COMMA 407
#define yykw_end 408
#define yykw_axiom 409
#define yytk_COLON 410
#define yytk_d_BLANK_e_BLANK_v_BLANK_t_BLANK_UNDERSCORE_r_BLANK_e_BLANK_l_BLANK_a_BLANK_t_BLANK_i_BLANK_o_BLANK_n_BLANK 411
#define yykw_theory 412
#define yykw_object 413
#define yykw_scheme 414
